export default [
"A conspiracy theorist's dream vacation.",
"Confessing to a crime I didn't commit.",
"Grandma's secret stash of adult toys.",
"Failed cooking experiments turned into avant-garde art.",
"Turning into a penguin whenever I'm nervous.",
"A chicken with a questionable past.",
"Dinosaurs hosting a wild party before extinction.",
"Bigfoot's fashion-forward choices.",
"Hobbits sneaking second breakfast at 11 AM.",
"A gritty reboot of \"My Little Pony.\"",
"Worshiping the holy trinity: bacon, Netflix, and WiFi.",
"The moon made entirely of cheese. Brie, to be specific.",
"Bursting into song about tax evasion during an audit.",
"A pet cat with the ability to speak in Shakespearean insults.",
"Finding inner peace through interpretive dance.",
"Sharing pictures of cats wearing tiny hats on the internet.",
"The title of my rap album: \"Straight Outta Tofu.\"",
"Leprechauns guarding a pot of artisanal kale smoothies.",
"Bringing up the topic of existential dread at family dinner.",
"Superhero retirement due to an addiction to napping.",
"The royal wedding featuring a statue of Elvis Presley.",
"Accidentally texting my boss a list of dad jokes.",
"Santa's secret side hustle as a coal miner.",
"Professional cloud-watching as a legitimate career.",
"Trading in Bitcoin for compliments.",
"Celebrities competing in extreme knitting challenges.",
"Bizarre internet search history: \"Can cats salsa dance?\"",
"A diet consisting entirely of unicorn-shaped macarons.",
"Mad scientist replaced lab assistant with a rubber chicken.",
"Finding the nearest disco ball-themed party app.",
"The cause of global warming: too many hot takes.",
"A circus act involving flaming marshmallow juggling.",
"Family reunion theme: interpretive dance-off.",
"Time traveler avoids 21st century due to bad fashion choices.",
"A happy marriage secret: regular doses of chocolate.",
"Sixth sense for detecting WiFi passwords.",
"Autobiography titled \"Confessions of a lint roller enthusiast.\"",
"Grandma's cookies: a pinch of unicorn tears.",
"Scented candles inspired by the aroma of victory.",
"Loch Ness Monster stays hidden due to stage fright.",
"Career change to professional bubble-wrap popper.",
"Impressing a date with interpretive kazoo playing.",
"Trend in pet ownership: pocket-sized emotional support ninjas.",
"Invention combining a toaster with a fog machine.",
"Superhero therapy sessions for unresolved childhood issues.",
"Fashion trend: wearing inflatable sumo wrestler suits.",
"Autobiography title: \"My Life as a professional pancake flipper.\"",
"Accidentally ordered a lifetime supply of glitter. Regrets.",
"Aliens abducting humans for a karaoke competition.",
"Dream vacation: beach, cocktail, and a book on sarcasm.",
"A conspiracy theorist's secret handshake.",
"Confessing to loving pineapple pizza unironically.",
"Grandma's secret talent for beatboxing.",
"Failed cooking experiments repurposed as modern art installations.",
"Turning into a mime whenever I'm nervous.",
"A chicken's tell-all autobiography.",
"Dinosaurs hosting a talent show before extinction.",
"Bigfoot's favorite karaoke song.",
"Hobbits breaking into spontaneous dance-offs at 11 AM.",
"A gritty reboot of \"SpongeBob SquarePants.\"",
"Worshiping the holy trinity: caffeine, WiFi, and sarcasm.",
"The moon made entirely of recycled plastic bottles.",
"Bursting into song about existential crisis at a funeral.",
"A pet cat with a passion for interpretive dance.",
"Finding inner peace through interpretive knitting.",
"Sharing pictures of llamas wearing disco ball hats.",
"The title of my rap album: \"Mic Drop: A Cappella Edition.\"",
"Leprechauns guarding a pot of gluten-free goldfish crackers.",
"Bringing up the topic of interpretive yoga at family dinner.",
"Superhero retirement due to an addiction to bubble wrap popping.",
"The royal wedding featuring a surprise appearance by Godzilla.",
"Accidentally texting my boss an invitation to a marshmallow-roasting party.",
"Santa's secret side hustle as a stand-up comedian.",
"Professional nose-whistling as a legitimate career.",
"Trading in cryptocurrency for hugs.",
"Celebrities competing in extreme interpretive cooking challenges.",
"Bizarre internet search history: \"Can penguins skydive?\"",
"A diet consisting entirely of rainbow-colored smoothies.",
"Mad scientist replaced lab assistant with a sentient robot vacuum.",
"Finding the nearest pillow-fight-themed party app.",
"The cause of global warming: too many hot tub parties.",
"A circus act involving juggling flaming rubber chickens.",
"Family reunion theme: interpretive karaoke.",
"Time traveler avoids 21st century due to lack of time-travel-friendly clothing.",
"A happy marriage secret: regular doses of puns.",
"Sixth sense for detecting the location of missing socks.",
"Autobiography titled \"Confessions of a cereal box collector.\"",
"Grandma's cookies: a pinch of pixie dust.",
"Scented candles inspired by the aroma of freshly baked memes.",
"Loch Ness Monster stays hidden due to fear of public speaking.",
"Career change to professional invisible friend.",
"Impressing a date with interpretive puppetry.",
"Trend in pet ownership: pocket-sized emotional support ninjas with tiny capes.",
"Invention combining a blender with a foghorn.",
"Superhero therapy sessions for unresolved sidekick issues.",
"Fashion trend: wearing traffic cones as hats.",
"Autobiography title: \"My Life as a professional unicorn wrangler.\"",
"Accidentally ordered a lifetime supply of rubber chickens. No regrets.",
"Aliens abducting humans for a dance-off competition.",
"Dream vacation: mountain climbing, spaghetti eating, and a documentary on sloths.",
]