export default [
"What's the next big conspiracy theory the aliens are spreading?",
"In my autobiography, I confess to being addicted to ______.",
"Why did grandma hide ______ in the cookie jar?",
"What's the secret ingredient in my failed cooking experiment?",
"My superpower is the ability to turn into ______ whenever I'm nervous.",
"Why did the chicken cross the road? To get away from ______.",
"The real reason dinosaurs went extinct: ______.",
"What's the latest fashion trend that only Bigfoot seems to be following?",
"Instead of \"elevenses\" hobbits have a tradition of ______ at 11 AM.",
"The new Netflix series features a gritty reboot of ______.",
"I accidentally joined a cult that worships ______. Help!",
"In a shocking turn of events, scientists discovered that the moon is made entirely of ______.",
"What's the most inappropriate time to burst into song about ______?",
"Due to a mix-up at the genetic lab, my pet cat now has the ability to ______.",
"My new self-help book teaches you how to find inner peace through ______.",
"The real reason the internet was invented: to share pictures of ______.",
"What's the title of my upcoming rap album about life as a ______?",
"Instead of gold, leprechauns now guard a pot of ______ at the end of the rainbow.",
"The best way to spice up a boring family dinner is to bring up the topic of ______.",
"Why did the superhero retire? Too many encounters with ______.",
"The most awkward moment at the royal wedding was when they unveiled the statue of ______.",
"I accidentally sent a text to my boss that was meant for ______. Awkward!",
"What's the real reason Santa added coal to naughty kids' stockings?",
"My Tinder profile lists my profession as a professional ______ wrangler.",
"In the future, instead of currency, we'll all be trading in ______.",
"The new reality show features celebrities competing in extreme ______.",
"The reason my internet search history is so bizarre: I'm researching ______ for a novel.",
"I'm starting a new diet that consists entirely of ______. Wish me luck!",
"Why did the mad scientist replace his lab assistant with ______?",
"My new app helps you find the nearest ______-themed party.",
"The real cause of global warming: too many people using ______.",
"I accidentally joined a circus as the world's only ______-eating contortionist.",
"The theme for this year's family reunion is ______-themed costumes.",
"Why did the time traveler refuse to visit the 21st century? Too many sightings of ______.",
"What's the secret to a happy marriage? Regular doses of ______.",
"I have a sixth sense for detecting ______. It's both a blessing and a curse.",
"My autobiography is just a collection of embarrassing stories involving ______.",
"The secret ingredient in grandma's famous cookies: a pinch of ______.",
"I'm launching a line of scented candles inspired by the aroma of ______.",
"The real reason the Loch Ness Monster stays hidden: a fear of ______.",
"I'm considering a career change to become a professional ______ juggler.",
"The best way to impress your date is to show off your talent for ______.",
"The new trend in pet ownership: everyone wants a miniature ______.",
"My latest invention combines a toaster with a ______. Breakfast just got interesting!",
"Why did the superhero attend therapy? Issues with unresolved ______ from childhood.",
"The latest fashion trend is wearing ______ as accessories. It's avant-garde!",
"The title of my autobiography: \"Confessions of a ______ Addict.\"",
"I accidentally ordered a lifetime supply of ______. Anyone want to trade?",
"The real reason aliens keep abducting humans: an obsession with ______.",
"My dream vacation destination involves relaxing on a beach with a cocktail in one hand and ______ in the other.",
]